### PR TITLE
Define a Procfile for running the evaluator.

### PR DESCRIPTION
**Pull request by lowjoel**
@fonglh See if this is sufficient to set up new build infra?

### CODE REVIEW

**Comment by fonglh** [comment]
Do you still need Docker?

So to deploy this I configure the steps in the README as part of the deploy process, then use the system scripts to start?

**Comment by lowjoel** [comment]
Docker will be used later for spinning up containers for executing the submitted code.

This repo is actually just a daemon process that will poll Coursemology for thing to evaluate...

**Comment by fonglh** [comment]
`foreman` runs and can generate upstart files.

I'm thinking through how to deploy it.

1. Checkout repo
1. `bundle install`
1. Copy the entire thing over to the deploy machine.
1. Run `foreman` for the Upstart scripts, copy to `/etc/init` on the deploy machine.
1. `sudo service evaluator start`

Is that about right?

**Comment by lowjoel** [comment]
Oh, that's what you mean.

I intended for this to be deployed via `gem install`, but I guess your steps could be fine. We can discuss this in the ops repo.

**Comment by fonglh** [comment]
Ok it seems sufficient then.

**Comment by lowjoel** [comment]
@allenwq can this be merged?

**Pull request merged**
