### PR TITLE
Initialize Docker

### PR DESCRIPTION
**Pull request by lowjoel**
@fonglh Please note that Docker is needed to be installed on the evaluators now. You can start provisioning them, and testing the build scripts.

Future PRs will add the actual evaluation, I anticipate within the next few days.

### CODE REVIEW

**Comment by lowjoel** [comment]
@allenwq I think the sleep line that isn't covered is nondeterministic.

**Comment by fonglh** [comment]
Are we combining this with the worker?

This is standalone right? Communications with the main app is through a REST API?

**Comment by fonglh** [comment]
DO has Docker as a 1 click app. I'll just use that.

**Comment by allenwq** [comment]
:+1:

**Comment by lowjoel** [comment]
@fonglh I'm not sure what the infra will look like in the beta stage.

This is standalone, communicates via REST. I need to push a PR to the web app to enable token authentication, but that requires me to PR to the gem that does that.

Just set up the service to make sure it boots with the system, and check that it works? Maybe we need to figure out how to collect logs for this thing also.

**Pull request merged**
