### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by allenwq**
Have released 0.1.1

### CODE REVIEW

**Comment by lowjoel** [comment]
already pushed to rubygems? should push straight to master in that case

**Comment by allenwq** [comment]
Yes, ok I will directly push to master for versions changes then.

**Comment by lowjoel** [comment]
You need to bundle update when you release a new version.

**Comment by allenwq** [comment]
Should we bundle update first and then directly release after that ?

**Comment by lowjoel** [comment]
I think maybe we should get rid of the bundle...

**Comment by allenwq** [comment]
Get rid of bundle ?

**Comment by lowjoel** [comment]
Okay. For this PR, do a `bundle update` first. Then commit together with the version change.

Next PR: delete Gemfile.lock, add to gitignore, then remove --production from Travis config.

**Comment by allenwq** [comment]
@lowjoel Updated.

**Pull request merged**
