### PR TITLE
Implement the evaluator skeleton

### PR DESCRIPTION
**Pull request by lowjoel**

### CODE REVIEW

**Comment by lowjoel** [comment]
@allenwq do you want to review this? :)

**Comment by allenwq** [comment]
Sure, this will give me a better understand of the whole framework.

**Comment by allenwq** [comment]
@lowjoel You are implementing a gem for the evaluator, how does this gem suppose to work ?  Will this it be installed in a rails app and handles requests ?

**Comment by lowjoel** [comment]
nope. just install the gem on the evaluator machine, set it up as a system service

**Comment by allenwq** [comment]
Then you will also add logic to let it be able to handle concurrent requests ?

**Comment by lowjoel** [comment]
probably not.

**Comment by lowjoel** [comment]
maybe in future? we only have one CPU on most of the small VMs

**Comment by allenwq** [comment]
Okay, thanks !

**Pull request merged**
