### PR TITLE
Implement collecting the exit code from the container.

### PR DESCRIPTION
**Pull request by lowjoel**

### CODE REVIEW

**Comment by lowjoel** [comment]
@allenwq I've no clue why Travis failing, you can run this on your local machine?

**Comment by allenwq** [comment]
OK, it only fails on this commit or it also fails on the merged commits ?

**Comment by lowjoel** [comment]
I think Travis has some configuration problem, it runs fine on my computer.

**Comment by allenwq** [comment]
Yeah, I set up the environment and tests passed on my local.

**Comment by lowjoel** [comment]
So, do we merge this?

**Comment by allenwq** [comment]
Sure

**Pull request merged**
